"""add user role

Revision ID: 46c562c4c9cc
Revises: e8398dd57c5c
Create Date: 2026-07-20 05:25:58.679317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

user_role_enum = postgresql.ENUM(
    "USER",
    "ADMIN",
    name="userrole",
    create_type=True,
)

# revision identifiers, used by Alembic.
revision: str = '46c562c4c9cc'
down_revision: Union[str, Sequence[str], None] = 'e8398dd57c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    user_role_enum.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', user_role_enum, nullable=False, server_default="USER",))
    # ### end Alembic commands ###
    op.alter_column("users", "role", server_default=None,)

def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
    user_role_enum.drop(bind, checkfirst=True)